src/problem/templates/problem/get.html
src/problem/templates/problem/list.html
src/problem/views.py

+ Show total points per problem list.

Hotfix: line break fix on problem description.

---

src/seminar/templates/seminar/list.html
src/seminar/urls.py

Fixed list.html, now the download link is working.

---

src/plus_study/urls.py
src/problem/templates/problem/get.html
src/problem/templates/problem/list.html
src/problem/urls.py
src/problem/views.py
src/seminar/templates/seminar/list.html
src/seminar/urls.py
src/seminar/views.py
src/website/templates/menu.html

Now uses url template rather than hardcoding.

Fixed URL Pattern

---

src/seminar/templates/seminar/list.html
src/seminar/urls.py
src/seminar/views.py

문제 리스트와 마찬가지로 세미나 리스트에서도 segment를 사용합니다.

Now seminar list uses segment.

---

src/problem/templates/problem/get.html
src/problem/views.py

client와 server 쪽에서 allow_question field를 의식하도록 바꿨습니다

Apply allow_question field

---

src/problem/helpers/score.py

Tweak performance by calling less DB queries
Resolves #47

Fix duplicate point calculation

---

src/problem/templates/problem/rank.html

https://www.chartjs.org/docs/latest/charts/line.html

lineTension to 0 (making graph straight line)

---

src/problem/templates/problem/get.html
src/website/templates/index.html

- 공지사항에 linebreak 추가
- 문제 description에 html tag unescape

Hotfix render template

---

src/problem/templates/problem/get.html

Hotfix render template 2

---

src/problem/views.py

qna answer now shows to every staff

---

src/problem/models.py

authlog - probleminstance CASCADE

---

src/problem/helpers/problem_info.py

problem sort by point & title

---

src/problem/helpers/problem_info.py
src/problem/templates/problem/user.html
src/problem/views.py
src/shop/views.py
src/website/views.py

Hotfix user view

---

src/problem/helpers/problem_info.py
src/problem/helpers/score.py
src/problem/views.py

#46 
문제 리스트마다 점수 추합하는 액션이 distributed points, first blood 시스템과 맞지 않아서 비효율적인듯.

Hotfix user view 2

---

src/problem/helpers/problem_info.py
src/problem/views.py

#46 
get_problem_list_user_score이라는 score만 계산하는 걸 따로 만들어서 훨씬 빠르게 했다. (그래도 좀 느림)

Hotfix user view 3

---

.circleci/config.yml
ci_requirements.txt
src/problem/templates/problem/list.html
src/problem/templates/problem/rank.html
src/problem/views.py
src/shop/views.py
src/website/templates/base.html

CI 의존성 라이브러리를 업데이트하면서, pylint에 맞게 코드를 수정했습니다.

Update CI dependencies

---

Dockerfile
docker-compose.yml
requirements.txt

테스트 환경에서 문제를 발견하지 못해, 버전을 업그레이드 했습니다.
- Python 3.8.2
- Django 3.1

Version Updates

---

src/problem/views.py

staff한테는 inactive session까지 다 보이게 하고, 
attachment download도 권한 확인
(#83 )

more and more fix on hidden problem downloads

---

README.md
docker-compose.override.dev.yml
docker-compose.override.production.reverse-proxy.yml
docker-compose.override.production.yml
docker-compose.yml
src/plus_study/settings.py

fix docker compose files and README

change config (#89)

---

requirements.txt
src/integration/admin.py
src/integration/apps.py
src/integration/helpers/discord.py
src/integration/models.py
src/integration/tests.py
src/integration/views.py
src/plus_study/settings.py
src/problem/__init__.py
src/problem/apps.py
src/problem/signals.py
src/problem/views.py

Discord Webhook 연동 기능이 추가되었습니다.
- Discord 인스턴스는 구독할 문제 목록과 전송할 이벤트를 선택할 수 있습니다.
- 선택할 수 있는 이벤트는 현재 총 6개 입니다.
- 퍼스트 블러드가 발생한 경우, 문제가 풀린 경우, 문제가 풀리지 않은 경우, 문제가 등록될 경우, 질문이 등록될 경우, 답변이 등록될 경우

Discord Integration Added

---

src/problem/admin.py
src/website/actions.py

Django Admin 페이지에서 CSV로 내보내는 기능을 추가했습니다.

Django Admin Actions: Export CSV

---

docker-compose.override.with-proxy.yml
nginx/conf.d/default.conf
nginx/vhost.d/default_location

New docker-compose settings for integrated nginx.

docker-compose.override.with-proxy.yml

---

requirements.txt

fix: set psycopg2-binary version to 2.8.6
